config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'urls#index', as: 'urls'
  get ':slug', to: 'urls#show', as: 'slug'
  get '/categories/:slug', to: 'categories#index', as: 'categories'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :urls

  before_create :set_slug!

  def to_s
    { id: id, name: name, slug: slug }
  end

  private

  def set_slug!
    self.slug = name.parameterize
  end

end

app/models/service/slug_generator.rb
class Service::SlugGenerator

  def self.call(identifier)
    SecureRandom.hex(2)
  end

end

app/models/service/url_shortener.rb
class Service::UrlShortener

  BASE_URL = "http://shre.xyz"

  def self.call(slug)
    "#{BASE_URL}/#{slug}"
  end

end

app/models/url.rb
class Url < ActiveRecord::Base

  has_many :url_clicks
  belongs_to :category

  before_create :define_uniq_slug!, if: ->() { slug.blank? }
  before_create :set_url_details!, if: ->() { title.blank? && description.blank? }

  scope :recents, -> { order(created_at: :desc).limit(10) }

  def to_s
    { id: id, origin: origin, slug: slug, clicks: clicks, created_at: created_at, updated_at: updated_at }
  end

  def increase_click!
    update_attribute(:clicks, clicks + 1)
  end

  private

  def define_uniq_slug!
    self.slug = Service::SlugGenerator.call(slug)
  end

  def set_url_details!
    page = MetaInspector.new(self.origin)
    self.title = page.title
    self.description = page.description
  end
end

app/models/url_click.rb
class UrlClick < ActiveRecord::Base

  belongs_to :url

  def to_s
    { id: id, url: url, browser: browser, platform: platform, ip: clicks, created_at: created_at, updated_at: updated_at }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :define_meta_tags!

  private

  def define_meta_tags!
    @meta = {
      title: 'Your short url with shre.xyz',
      description: 'A awesome list of links shared'
    }
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @title = load_category.name
    @urls = load_category.urls.recents
  end

  private

  def load_category
    @category ||= Category.find_by(slug: params[:slug])
  end

  def define_meta_tags!  
    @meta = { title: load_category.name, description: load_category.description }
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.recents
  end

  def show
    if load_url.nil?
      redirect_to urls_path
    else
      load_url.url_clicks.create!(browser: request.headers["User-Agent"], ip: request.ip)
      redirect_to load_url.origin if load_url.increase_click!
    end
  end

  private

  def load_url
    @url ||= Url.find_by(slug: params[:slug])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%= render 'urls/index', urls: @urls %>

app/views/layouts/application.html.erb
<!doctype html>
<html ⚡>
  <head>
    <title><%= @meta[:title] %></title>
    <meta name="description" content="<%= @meta[:description] %>">
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">

    <meta name="B-verify" content="840e1cccef9351868e6a6dee8efa58af03b9a447" />

    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
    <link rel="canonical" href="<%= request.original_url %>">

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

    <style amp-custom>
      html {
        background-color: #FAFAFA;
        color: #333;
        -webkit-font-smoothing: antialiased;
      }

      ul {
        list-style-type: none;
        margin-right: 30px;
      }

      .header {
        text-align: center;
        padding-top: 20px;
        padding-left: 40px;
        padding-right: 40px;
      }

      h1 {
        font-size: 22px;
      }

      h2 {
        font-size: 20px;
        font-weight: 300;
      }

      h3 {
        font-size: 18px;
      }

      .description {
        font-size: 16px;
        color: #7d7b7b;
      }

      footer {
        font-size: 22px;
      }

      footer ul li {
        margin-top: 15px;
      }

      .container {
        margin: 0 auto;
      }

      .article {
        padding-top: 20px;
        padding-bottom: 20px;
        border-bottom: 1px solid #ccc;
      }

      .link-article {
        font-size: 22px;
      }

    </style>

  </head>

  <body itemscope itemtype='http://schema.org/WebPage'>
    <div class='container'>

      <div class="header">
        <h1 itemprop="name"><%= @meta[:title] %></h1>
        <h2 itemprop="description"><%= @meta[:description] %></h2>
      </div>

      <%= yield %>

      <footer>
        <ul>
          <li><%= link_to 'Inicio', urls_path %></li>
          <% Category.all.each do |category| %>
            <li><%= link_to category.name, categories_path(category.slug), class: 'link-category' %></li>
          <% end %>
        </ul>
      </footer>

    </div>

    <amp-analytics type="googleanalytics">
      <script type="application/json">
        {
          "vars": {
            "account": "UA-107277241-1"
          },
          "triggers": {
            "trackPageview": {
              "on": "visible",
              "request": "pageview"
            },
            "trackClickOnFooter": {
              "selector": ".link-category",
              "on": "click",
              "request": "event",
              "vars": {
                "eventCategory": "footer-url",
                "eventAction": "click"
              }
            },
            "trackClickOnArticle": {
              "selector": ".link-article",
              "on": "click",
              "request": "event",
              "vars": {
                "eventCategory": "article-url",
                "eventAction": "click"
              }
            }
          }
        }
      </script>
    </amp-analytics>

  </body>

</html>

app/views/urls/_index.html.erb
<ul>
  <% urls.each do |url| %>
    <li class='article'>
      <h3><%= url.title %></h3>
      <p class='description'><%= url.description %></p>
      <%= link_to "http://shre.xyz/#{url.slug}", "http://shre.xyz/#{url.slug}", class: 'link-article' %>
    </li>
  <% end %>
</ul>

app/views/urls/index.html.erb
<ul>
<% @urls.each do |url| %>
  <li>
    <div class="date">
      <%= url.created_at.strftime('%F') %>
    </div>
    <%= link_to url.origin %> (<%= url.clicks %> clicks)
<% end %>
</ul>